# Generated by Django 5.0.3 on 2025-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='dias',
            field=models.CharField(blank=True, choices=[('', 'Sin día asignado'), ('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIÉRCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SÁBADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='', help_text='Día en que se dicta el módulo', max_length=20),
        ),
    ]
