# Generated by Django 5.0.3 on 2025-02-27 03:08

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantePen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Estudiante')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Estudiante Pen',
                'verbose_name_plural': 'Estudiantes Pen',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='modulos',
            name='dias',
            field=models.CharField(blank=True, choices=[('', 'Sin día asignado'), ('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIÉRCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SÁBADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='', help_text='Día en que se dicta el módulo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIÉRCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SÁBADO', 'Sábado'), ('DOMINGO', 'Domingo')], help_text='Días en que se dicta el curso', max_length=52),
        ),
        migrations.CreateModel(
            name='InscripcionPen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.cursos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.estudiantepen')),
            ],
            options={
                'verbose_name': 'Inscripción Pen',
                'verbose_name_plural': 'Inscripciones Pen',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
