# Generated by Django 5.0.3 on 2025-02-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_inscripcion_localidad_inscripcion_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='lugar',
            field=models.CharField(choices=[('SEDE', 'Sede'), ('SUB_SEDE', 'Sub sede'), ('ANEXO', 'Anexo')], default='SEDE', help_text='Ubicación física donde se dicta el curso', max_length=20),
        ),
    ]
