# Generated by Django 5.0.3 on 2025-02-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_estudiantepen_dni'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='inscripcionpen',
            name='dni_frente_pen',
            field=models.ImageField(blank=True, upload_to='dni_frente_pen/'),
        ),
        migrations.AddField(
            model_name='inscripcionpen',
            name='dni_reverso_pen',
            field=models.ImageField(blank=True, upload_to='dni_reverso_pen/'),
        ),
        migrations.AddField(
            model_name='inscripcionpen',
            name='varios_pen',
            field=models.FileField(blank=True, upload_to='varios_pen/'),
        ),
    ]
