# Generated by Django 5.0.3 on 2025-02-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_cursos_inscripcion_abierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='cursando',
            field=models.BooleanField(default=True, help_text='Indica si el curso ya comenzo'),
        ),
    ]
