# Generated by Django 5.0.3 on 2025-02-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_cursos_dias'),
        ('cursos', '0004_estudiantepen_dni'),
        ('cursos', '0007_cursos_dias_cursos_horario_fin_cursos_horario_inicio_and_more'),
    ]

    operations = [
    ]
