# Generated by Django 5.0.3 on 2025-02-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_merge_20250227_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionpen',
            name='analitico_primaria_pen',
            field=models.ImageField(blank=True, null=True, upload_to='analitico_primaria_pen/'),
        ),
        migrations.AddField(
            model_name='inscripcionpen',
            name='dni_frente_pen',
            field=models.ImageField(blank=True, upload_to='dni_frente_pen/'),
        ),
        migrations.AddField(
            model_name='inscripcionpen',
            name='dni_reverso_pen',
            field=models.ImageField(blank=True, upload_to='dni_reverso_pen/'),
        ),
        migrations.AddField(
            model_name='inscripcionpen',
            name='maximo_alcanzado',
            field=models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], default='PRIMARIA', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcionpen',
            name='varios_pen',
            field=models.FileField(blank=True, upload_to='varios_pen/'),
        ),
    ]
