# Generated by Django 5.0.3 on 2025-03-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_inscripcionpen_maximo_alcanzado'),
        ('cursos', '0009_inscripcionpen_analitico_primaria_pen_and_more'),
    ]

    operations = [
    ]
