# Generated by Django 5.1.6 on 2025-03-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_remove_estudiantepen_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='analitico_primaria_dorso',
            field=models.ImageField(blank=True, default=None, help_text='Imagen del dorso del analítico de primaria.', null=True, upload_to='analitico_primaria_dorso/'),
        ),
    ]
