# Generated by Django 5.1.6 on 2025-03-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_inscripcion_analitico_primaria_dorso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='analitico_primaria',
            field=models.FileField(blank=True, null=True, upload_to='analitico_primaria/'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='analitico_primaria_dorso',
            field=models.FileField(blank=True, default=None, help_text='Imagen del dorso del analítico de primaria.', null=True, upload_to='analitico_primaria_dorso/'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='dni_frente',
            field=models.FileField(upload_to='dni_frente/'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='dni_reverso',
            field=models.FileField(upload_to='dni_reverso/'),
        ),
    ]
