# Generated by Django 5.2 on 2025-08-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_inscripcion_analitico_primaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('media_falta', 'Media Falta')], default='ausente', max_length=12),
        ),
    ]
