# Generated by Django 5.2.8 on 2026-01-29 19:17

import cuentas.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_alter_asistencia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='analitico_primaria',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='analitico_primaria_dorso',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='dni_reverso',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='analitico_1',
            field=models.ImageField(blank=True, null=True, upload_to=cuentas.utils.generar_ruta_inscripcion),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='analitico_2',
            field=models.ImageField(blank=True, null=True, upload_to=cuentas.utils.generar_ruta_inscripcion),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='analitico_3',
            field=models.ImageField(blank=True, null=True, upload_to=cuentas.utils.generar_ruta_inscripcion),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='analitico_4',
            field=models.ImageField(blank=True, null=True, upload_to=cuentas.utils.generar_ruta_inscripcion),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='dni_dorso',
            field=models.ImageField(blank=True, null=True, upload_to=cuentas.utils.generar_ruta_inscripcion),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='constancia_cuil',
            field=models.ImageField(blank=True, null=True, upload_to=cuentas.utils.generar_ruta_inscripcion),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='dni_frente',
            field=models.ImageField(blank=True, null=True, upload_to=cuentas.utils.generar_ruta_inscripcion),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='dni_numero',
            field=models.CharField(max_length=20, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
