# Generated by Django 5.2.8 on 2026-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_remove_inscripcion_analitico_primaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='entrega_certificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='pago_contribucion',
            field=models.BooleanField(default=False),
        ),
    ]
