# Generated by Django 5.2.8 on 2026-02-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_inscripcion_entrega_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='inscripcion_fisica',
            field=models.BooleanField(default=False, help_text='Indica si el estudiante entregó la documentación física.'),
        ),
    ]
