# Generated by Django 5.2.8 on 2026-02-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_inscripcion_inscripcion_fisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estudia_otro_lado',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Estás estudiando en otro lugar?'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='horario_estudio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Días y horarios de estudio'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='horario_trabajo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Días y horarios de trabajo'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='trabaja',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Estás trabajando?'),
        ),
    ]
