# Generated by Django 5.2.8 on 2026-02-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_inscripcion_estudia_otro_lado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el curso.', null=True, verbose_name='Fecha de creación'),
        ),
    ]
