# Generated by Django 5.0.3 on 2026-04-13 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_cursos_fecha_creacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantesEliminados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Motivo por el cual el estudiante fue eliminado del curso.')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_eliminados', to='cursos.cursos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminaciones_como_estudiante', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminaciones_como_instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante Eliminado',
                'verbose_name_plural': 'Estudiantes Eliminados',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
    ]
