# Generated by Django 6.0.7 on 2026-07-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_estudianteseliminados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='mensaje_inscripcion',
            field=models.TextField(blank=True, help_text='Este mensaje se enviará por email automáticamente al estudiante cuando se pre-inscriba.', null=True, verbose_name='Mensaje para alumnos inscriptos'),
        ),
    ]
