# Generated by Django 5.0.3 on 2025-02-21 21:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE cursos_modulos DROP COLUMN dias;",
            "ALTER TABLE cursos_modulos ADD COLUMN dias varchar(20);"
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='El nombre no puede tener más de 25 caracteres.', max_length=255)),
                ('descripcion', models.TextField(help_text='Campo de texto largo.')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del curso.')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización del curso.')),
                ('max_estudiantes', models.PositiveIntegerField(help_text='Número máximo de estudiantes permitidos en el curso.')),
                ('grupo_familia', models.CharField(help_text='Grupo o familia al que pertenece el curso.', max_length=100)),
                ('aprobado', models.BooleanField(default=False)),
                ('lugar', models.CharField(choices=[('SEDE', 'Sede'), ('SUB_SEDE', 'Sub sede'), ('ANEXO', 'Anexo')], default='SEDE', help_text='Ubicación física donde se dicta el curso', max_length=20)),
                ('inscripcion_abierta', models.BooleanField(default=True, help_text='Indica si las inscripciones están abiertas para este curso.')),
                ('cursando', models.BooleanField(default=True, help_text='Indica si el curso ya comenzó')),
                ('horario_inicio', models.TimeField(blank=True, help_text='Horario de inicio del curso', null=True)),
                ('horario_fin', models.TimeField(blank=True, help_text='Horario de finalización del curso', null=True)),
                ('dias', models.CharField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIÉRCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SÁBADO', 'Sábado'), ('DOMINGO', 'Domingo')], help_text='Día en que se dicta el curso', max_length=20)),
                ('alumnos_inscriptos', models.ManyToManyField(blank=True, help_text='Relación muchos a muchos con alumnos inscritos.', related_name='cursos_inscriptos', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(help_text='Instructor del curso. Solo usuarios con rol de instructor pueden ser asignados.', on_delete=django.db.models.deletion.CASCADE, related_name='cursos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='cursos.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('dni_numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Número de DNI')),
                ('dni_frente', models.ImageField(upload_to='dni_frente/')),
                ('dni_reverso', models.ImageField(upload_to='dni_reverso/')),
                ('constancia_cuil', models.FileField(upload_to='constancia_cuil/')),
                ('analitico_primaria', models.ImageField(blank=True, null=True, upload_to='analitico_primaria/')),
                ('partido', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('estudios_maximos', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del módulo.', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción detallada del módulo.')),
                ('recursos', models.FileField(blank=True, help_text='Solo archivos PDF.', upload_to='modulos/recursos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('carga_horaria', models.IntegerField(help_text='Ingrese la carga horaria del módulo.')),
                ('fecha_inicio_modulo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin_modulo', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.FloatField(default=0.0, help_text='Nota obtenida por los estudiantes en el módulo. Debe estar entre 0 y 100.')),
                ('estado_aprobado', models.BooleanField(default=False, help_text='Indica si el módulo está aprobado o no.')),
                ('instructor', models.ForeignKey(help_text='Instructor responsable del módulo.', on_delete=django.db.models.deletion.CASCADE, related_name='modulos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='modulos',
            field=models.ManyToManyField(blank=True, help_text='Módulos que integran el curso.', related_name='cursos_asociados', to='cursos.modulos'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='ausente', max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.clase')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.cursos')),
            ],
            options={
                'unique_together': {('clase', 'estudiante', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(default=0.0, help_text='Nota del estudiante en el módulo (de 0 a 100).')),
                ('fecha_asignacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que se asignó la nota.')),
                ('estudiante', models.ForeignKey(help_text='Estudiante que recibe la nota.', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(help_text='Módulo al que pertenece la nota.', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='cursos.modulos')),
            ],
            options={
                'unique_together': {('estudiante', 'modulo')},
            },
        ),
    ]
