# Generated by Django 5.0.3 on 2025-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='dni_numero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número de DNI'),
        ),
    ]
