# Generated by Django 5.0.3 on 2025-02-21 21:42

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_modulos_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIÉRCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SÁBADO', 'Sábado'), ('DOMINGO', 'Domingo')], help_text='Días en que se dicta el curso', max_length=52),
        ),
    ]
