# Generated by Django 5.0.3 on 2025-02-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_inscripcion_dni_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='partido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
