# Generated by Django 5.0.3 on 2025-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_estudiantepen_modulos_dias_alter_cursos_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='alumnos_inscriptos_pen',
            field=models.ManyToManyField(blank=True, help_text='Relación muchos a muchos con alumnos inscritos en el sistema Pen.', related_name='cursos_inscriptos_pen', to='cursos.estudiantepen'),
        ),
    ]
