# Generated by Django 5.0.3 on 2025-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursos_alumnos_inscriptos_pen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantepen',
            name='dni',
            field=models.CharField(default='0000', max_length=20, unique=True, verbose_name='DNI'),
        ),
    ]
