# Generated by Django 5.0.3 on 2025-02-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_cursos_lugar'),
    ]

    operations = [
            ]
