# Generated by Django 5.0.3 on 2025-02-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_inscripcionpen_analitico_primaria_pen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionpen',
            name='maximo_alcanzado',
            field=models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], default='PRIMARIA', max_length=20),
        ),
    ]
