# Generated by Django 5.0.3 on 2025-02-21 22:52

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_cursos_cursando'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIÉRCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SÁBADO', 'Sábado'), ('DOMINGO', 'Domingo')], help_text='Días en que se dicta el curso', max_length=52),
        ),
        migrations.AddField(
            model_name='cursos',
            name='horario_fin',
            field=models.TimeField(blank=True, help_text='Horario de finalización del curso', null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='horario_inicio',
            field=models.TimeField(blank=True, help_text='Horario de inicio del curso', null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='dias',
            field=models.CharField(blank=True, choices=[('', 'Sin día asignado'), ('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIÉRCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SÁBADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='', help_text='Día en que se dicta el módulo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='cursando',
            field=models.BooleanField(default=True, help_text='Indica si el curso ya comenzó'),
        ),
    ]
