# Generated by Django 5.0.3 on 2025-03-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_merge_20250309_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantepen',
            name='email',
        ),
    ]
