# Generated by Django 5.0.3 on 2025-02-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('instructor', 'Instructor'), ('directivo', 'Directivo'), ('adminpenin', 'AdminPenin')], default='alumno', max_length=10),
        ),
    ]
