# Generated by Django 5.0.3 on 2025-02-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_profile_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('instructor', 'Instructor'), ('directivo', 'Directivo')], default='alumno', max_length=10),
        ),
    ]
