# Generated by Django 5.1.6 on 2025-03-03 21:14

from django.db import migrations, models
import django.utils.timezone as timezone

class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_profile_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='asunto',
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
