# Generated by Django 5.1.6 on 2025-03-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_remove_contacto_asunto_contacto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
