# Generated by Django 5.0.3 on 2025-05-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_contacto_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionCelulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('puntaje_objetivo', models.IntegerField()),
                ('respuestas_objetivas', models.JSONField()),
                ('respuestas_abiertas', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
