# Generated by Django 5.0.3 on 2025-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_evaluacioncelulares'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncelulares',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evaluacioncelulares',
            name='dni',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluacioncelulares',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
