# Generated by Django 5.2.8 on 2026-01-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_profile_avatar_profile_bio_profile_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
