# Generated by Django 5.2.8 on 2026-01-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0014_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_version',
            field=models.IntegerField(default=0),
        ),
    ]
