# Generated by Django 5.0.3 on 2024-08-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('formulario', '0002_curso_remove_inscripcion_curso_inscripcion_edad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='cursos',
            field=models.ManyToManyField(to='cursos.curso'),
        ),
    ]
