# choices.py

PARTIDOS_PRINCIPALES = [
    ('', 'Seleccione un partido'),
    ('La Matanza', 'La Matanza'),
    ('Merlo', 'Merlo'),
    ('Moreno', 'Moreno'),
    ('Morón', 'Morón'),
    ('Ituzaingó', 'Ituzaingó'),
    ('Hurlingham', 'Hurlingham'),
    ('Tres de Febrero', 'Tres de Febrero'),
    ('San Martín', 'General San Martín'),
    ('San Miguel', 'San Miguel'),
    ('Malvinas Argentinas', 'Malvinas Argentinas'),
    ('José C. Paz', 'José C. Paz'),
    ('Pilar', 'Pilar'),
    ('Marcos Paz', 'Marcos Paz'),
    ('Cañuelas', 'Cañuelas'),
    ('Ezeiza', 'Ezeiza'),
    ('Esteban Echeverría', 'Esteban Echeverría'),
    ('Almirante Brown', 'Almirante Brown'),
    ('Lomas de Zamora', 'Lomas de Zamora'),
    ('Quilmes', 'Quilmes'),
    ('Florencio Varela', 'Florencio Varela'),
    ('Berazategui', 'Berazategui'),
    ('Lanús', 'Lanús'),
    ('Avellaneda', 'Avellaneda'),
    ('Otro', 'Otro (especificar en Dirección)'),
]

LOCALIDADES_POR_PARTIDO = {
    'La Matanza': [
        ('', 'Seleccione localidad'),
        ('Aldo Bonzi', 'Aldo Bonzi'),
        ('Ciudad Evita', 'Ciudad Evita'),
        ('González Catán', 'González Catán'),
        ('Gregorio de Laferrere', 'Gregorio de Laferrere'),
        ('Isidro Casanova', 'Isidro Casanova'),
        ('La Tablada', 'La Tablada'),
        ('Lomas del Mirador', 'Lomas del Mirador'),
        ('Rafael Castillo', 'Rafael Castillo'),
        ('Ramos Mejía', 'Ramos Mejía'),
        ('San Justo', 'San Justo'),
        ('Tapiales', 'Tapiales'),
        ('Villa Luzuriaga', 'Villa Luzuriaga'),
        ('Virrey del Pino', 'Virrey del Pino'),
        ('20 de Junio', '20 de Junio'),
    ],
    'Merlo': [
        ('', 'Seleccione localidad'),
        ('Merlo', 'Merlo'),
        ('Libertad', 'Libertad'),
        ('Mariano Acosta', 'Mariano Acosta'),
        ('Pontevedra', 'Pontevedra'),
        ('San Antonio de Padua', 'San Antonio de Padua'),
        ('Parque San Martín', 'Parque San Martín'),
    ],
    'Moreno': [
        ('', 'Seleccione localidad'),
        ('Moreno', 'Moreno'),
        ('Cuartel V', 'Cuartel V'),
        ('Francisco Álvarez', 'Francisco Álvarez'),
        ('La Reja', 'La Reja'),
        ('Paso del Rey', 'Paso del Rey'),
        ('Trujui', 'Trujui'),
    ],
    'Morón': [
        ('', 'Seleccione localidad'),
        ('Morón', 'Morón'),
        ('Castelar', 'Castelar'),
        ('El Palomar', 'El Palomar'),
        ('Haedo', 'Haedo'),
        ('Villa Sarmiento', 'Villa Sarmiento'),
    ],
    'Ituzaingó': [
        ('', 'Seleccione localidad'),
        ('Ituzaingó', 'Ituzaingó'),
        ('Ituzaingó Sur', 'Ituzaingó Sur'),
    ],
    'Hurlingham': [
        ('', 'Seleccione localidad'),
        ('Hurlingham', 'Hurlingham'),
        ('Villa Tesei', 'Villa Tesei'),
        ('William C. Morris', 'William C. Morris'),
    ],
    'Tres de Febrero': [
        ('', 'Seleccione localidad'),
        ('Caseros', 'Caseros'),
        ('Churruca', 'Churruca'),
        ('Ciudad Jardín', 'Ciudad Jardín'),
        ('Ciudadela', 'Ciudadela'),
        ('El Libertador', 'El Libertador'),
        ('José Ingenieros', 'José Ingenieros'),
        ('Loma Hermosa', 'Loma Hermosa'),
        ('Martín Coronado', 'Martín Coronado'),
        ('Once de Septiembre', 'Once de Septiembre'),
        ('Pablo Podestá', 'Pablo Podestá'),
        ('Remedios de Escalada', 'Remedios de Escalada'),
        ('Santos Lugares', 'Santos Lugares'),
        ('Sáenz Peña', 'Sáenz Peña'),
        ('Villa Bosch', 'Villa Bosch'),
        ('Villa Raffo', 'Villa Raffo'),
    ],
    'San Martín': [
        ('', 'Seleccione localidad'),
        ('San Martín', 'San Martín'),
        ('Villa Ballester', 'Villa Ballester'),
        ('Villa Lynch', 'Villa Lynch'),
        ('Villa Maipú', 'Villa Maipú'),
    ],
    'San Miguel': [
        ('', 'Seleccione localidad'),
        ('San Miguel', 'San Miguel'),
        ('Bella Vista', 'Bella Vista'),
        ('Muñiz', 'Muñiz'),
        ('Santa María', 'Santa María'),
    ],
    'Malvinas Argentinas': [
        ('', 'Seleccione localidad'),
        ('Grand Bourg', 'Grand Bourg'),
        ('Ingeniero Pablo Nogués', 'Ingeniero Pablo Nogués'),
        ('Los Polvorines', 'Los Polvorines'),
        ('Tortuguitas', 'Tortuguitas'),
        ('Villa de Mayo', 'Villa de Mayo'),
    ],
    'José C. Paz': [
        ('', 'Seleccione localidad'),
        ('José C. Paz', 'José C. Paz'),
    ],
    'Pilar': [
        ('', 'Seleccione localidad'),
        ('Pilar', 'Pilar'),
        ('Del Viso', 'Del Viso'),
        ('Derqui', 'Derqui'),
        ('Manzanares', 'Manzanares'),
        ('Villa Astolfi', 'Villa Astolfi'),
        ('Zelaya', 'Zelaya'),
    ],
    'Marcos Paz': [
        ('', 'Seleccione localidad'),
        ('Marcos Paz', 'Marcos Paz'),
    ],
    'Cañuelas': [
        ('', 'Seleccione localidad'),
        ('Cañuelas', 'Cañuelas'),
        ('Uribelarrea', 'Uribelarrea'),
        ('Alejandro Petión', 'Alejandro Petión'),
    ],
    'Ezeiza': [
        ('', 'Seleccione localidad'),
        ('Ezeiza', 'Ezeiza'),
        ('Carlos Spegazzini', 'Carlos Spegazzini'),
        ('Tristán Suárez', 'Tristán Suárez'),
    ],
    'Esteban Echeverría': [
        ('', 'Seleccione localidad'),
        ('Monte Grande', 'Monte Grande'),
        ('9 de Abril', '9 de Abril'),
        ('Canning', 'Canning'),
        ('El Jagüel', 'El Jagüel'),
        ('Luis Guillón', 'Luis Guillón'),
    ],
    'Almirante Brown': [
        ('', 'Seleccione localidad'),
        ('Adrogué', 'Adrogué'),
        ('Burzaco', 'Burzaco'),
        ('Claypole', 'Claypole'),
        ('Don Orione', 'Don Orione'),
        ('Glew', 'Glew'),
        ('José Mármol', 'José Mármol'),
        ('Longchamps', 'Longchamps'),
        ('Rafael Calzada', 'Rafael Calzada'),
        ('Malvinas Argentinas', 'Malvinas Argentinas'),
    ],
    'Lomas de Zamora': [
        ('', 'Seleccione localidad'),
        ('Banfield', 'Banfield'),
        ('Llavallol', 'Llavallol'),
        ('Lomas de Zamora', 'Lomas de Zamora'),
        ('Temperley', 'Temperley'),
        ('Turdera', 'Turdera'),
        ('Villa Centenario', 'Villa Centenario'),
        ('Villa Fiorito', 'Villa Fiorito'),
    ],
    'Quilmes': [
        ('', 'Seleccione localidad'),
        ('Quilmes', 'Quilmes'),
        ('Bernal', 'Bernal'),
        ('Don Bosco', 'Don Bosco'),
        ('Ezpeleta', 'Ezpeleta'),
        ('San Francisco Solano', 'San Francisco Solano'),
        ('Villa La Florida', 'Villa La Florida'),
    ],
    'Florencio Varela': [
        ('', 'Seleccione localidad'),
        ('Florencio Varela', 'Florencio Varela'),
        ('Bosques', 'Bosques'),
        ('Ingeniero Juan Allan', 'Ingeniero Juan Allan'),
        ('Villa Brown', 'Villa Brown'),
        ('Villa San Luis', 'Villa San Luis'),
        ('Villa Vatteone', 'Villa Vatteone'),
        ('Villa Santa Rosa', 'Villa Santa Rosa'),
    ],
    'Berazategui': [
        ('', 'Seleccione localidad'),
        ('Berazategui', 'Berazategui'),
        ('Berazategui Oeste', 'Berazategui Oeste'),
        ('El Pato', 'El Pato'),
        ('Guillermo E. Hudson', 'Guillermo E. Hudson'),
        ('Juan María Gutiérrez', 'Juan María Gutiérrez'),
        ('Pereyra', 'Pereyra'),
        ('Plátanos', 'Plátanos'),
        ('Ranelagh', 'Ranelagh'),
        ('Villa España', 'Villa España'),
    ],
    'Lanús': [
        ('', 'Seleccione localidad'),
        ('Lanús', 'Lanús'),
        ('Lanús Este', 'Lanús Este'),
        ('Monte Chingolo', 'Monte Chingolo'),
        ('Remedios de Escalada', 'Remedios de Escalada'),
        ('Valentín Alsina', 'Valentín Alsina'),
    ],
    'Avellaneda': [
        ('', 'Seleccione localidad'),
        ('Avellaneda', 'Avellaneda'),
        ('Crucesita', 'Crucesita'),
        ('Dock Sud', 'Dock Sud'),
        ('Gerli', 'Gerli'),
        ('Piñeyro', 'Piñeyro'),
        ('Sarandí', 'Sarandí'),
        ('Villa Dominico', 'Villa Dominico'),
        ('Wilde', 'Wilde'),
    ],
    'Otro': [
        ('', 'Si seleccionó Otro, especifique en Dirección'),
    ],
}