# Generated by Django 5.2.7 on 2025-10-27 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('imagen_desktop', models.ImageField(upload_to='anuncios/desktop/')),
                ('imagen_movil', models.ImageField(blank=True, null=True, upload_to='anuncios/movil/')),
                ('texto_promocional', models.CharField(help_text='Texto que irá en la franja superior', max_length=200)),
                ('url_destino', models.URLField(blank=True, help_text='URL opcional del CTA dentro del popup', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.PositiveIntegerField(default=10, help_text='Menor número = más prioridad')),
                ('mostrar_una_vez_por_dia', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['prioridad', '-fecha_inicio'],
            },
        ),
    ]
