# Generated by Django 5.2.7 on 2025-10-27 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Usá 10 dígitos: 1122334455')]),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='prioridad',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='texto_promocional',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='url_destino',
            field=models.URLField(blank=True, null=True),
        ),
    ]
