# Generated by Django 5.2.7 on 2025-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_anuncio_whatsapp_alter_anuncio_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='mensaje_predefinido',
            field=models.TextField(blank=True, help_text='Mensaje que se enviará automáticamente cuando el usuario haga clic en la imagen', null=True),
        ),
    ]
