# Generated by Django 5.2.7 on 2025-10-27 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_anuncio_mensaje_predefinido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='anuncios.anuncio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_anuncio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['anuncio', 'timestamp'], name='anuncios_cl_anuncio_338084_idx'), models.Index(fields=['anuncio', 'usuario', 'timestamp'], name='anuncios_cl_anuncio_0ab940_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpresionAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impresiones', to='anuncios.anuncio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impresiones_anuncio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['anuncio', 'timestamp'], name='anuncios_im_anuncio_9033d0_idx'), models.Index(fields=['anuncio', 'usuario', 'timestamp'], name='anuncios_im_anuncio_c1da93_idx')],
            },
        ),
    ]
