# Generated by Django 5.2.8 on 2026-02-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_clickanuncio_impresionanuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='texto_promocional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
