# Generated by Django 5.2.8 on 2026-01-21 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje_socket',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socket_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje_socket',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socket_recibidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
