# Generated by Django 5.2.8 on 2026-01-21 21:44

import mensajes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_mensaje_socket_emisor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje_socket',
            options={},
        ),
        migrations.RenameField(
            model_name='mensaje_socket',
            old_name='leido',
            new_name='es_imagen',
        ),
        migrations.AddField(
            model_name='mensaje_socket',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='chat_archivos/%Y/%m/%d/', validators=[mensajes.models.validar_peso_archivo]),
        ),
        migrations.AlterField(
            model_name='mensaje_socket',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
