# Generated by Django 5.2.8 on 2026-01-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_alter_mensaje_socket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje_socket',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
